### ISSUE TITLE
Please update the "About" description to "Red Hat OpenShift Dev Spaces"

### ISSUE THREAD

**Issue by karstengresch** [redhat-developer/devspaces-chectl#124]
The "About" information of this project is:

```
CodeReady Workspaces build of chectl, based on (...)
```

but should be IMHO

```
Red Hat OpenShift Dev Spaces build of chectl, based on (...)
```

**Comment by nickboldt** [comment]
Done:

<img width="170" alt="image" src="https://github.com/redhat-developer/devspaces-chectl/assets/227597/08dee9b7-6793-4ffb-97e1-d3e4be770b00">
